Repository DesignLiquido/delegua, pull requests merged in 2023-10, with the labels that each got.

#525 #524 inicializando e escrevendo vetores
  .vscode/extensions.json
  .vscode/launch.json
  fontes/analisador-semantico/README.md
  fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
  fontes/bibliotecas/dialetos/potigol/primitivas-vetor.ts
  fontes/interpretador/interpretador-base.ts
  testes/potigol/interpretador.test.ts
Labels: potigol

#528 WIP: [potigol] - implementação qual_tipo
  .vscode/launch.json
  fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
  fontes/construtos/index.ts
  fontes/construtos/qual-tipo.ts
  fontes/interfaces/interpretador-interface-potigol.ts
  fontes/interpretador/dialetos/egua-classico/interpretador-egua-classico.ts
  fontes/interpretador/dialetos/egua-classico/resolvedor/resolvedor.ts
  fontes/interpretador/dialetos/portugol-ipt/interpretador-portugol-ipt.ts
  fontes/interpretador/dialetos/potigol/inferenciador.ts
  fontes/interpretador/dialetos/potigol/interpretador-potigol.ts
  fontes/interpretador/interpretador-base.ts
  fontes/lexador/dialetos/palavras-reservadas/potigol.ts
  fontes/tipos-de-simbolos/potigol.ts
  testes/interpretador.test.ts
  testes/potigol/avaliador-sintatico.test.ts
  testes/potigol/interpretador.test.ts
Labels: em andamento

#540 536 melhorar testes unitários que chamam escreva
  testes/interpretador.test.ts
Labels: melhoria
