Repository DesignLiquido/delegua, pull requests merged in 2023-03, with the labels that each got.

#290 Birl
  .vscode/launch.json
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-birl.ts
  fontes/lexador/dialetos/lexador-birl.ts
  fontes/lexador/dialetos/palavras-reservadas/birl.ts
  fontes/tipos-de-simbolos/birl.ts
  testes/birl/avaliador-sintatico.test.ts
  testes/birl/lexador.test.ts
Labels: melhoria

#291 Birl
  fontes/avaliador-sintatico/avaliador-sintatico-base.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-birl.ts
  fontes/lexador/dialetos/palavras-reservadas/birl.ts
  fontes/tipos-de-simbolos/birl.ts
  testes/birl/avaliador-sintatico.test.ts
Labels: melhoria, em andamento

#298 Base para traduzir VisuAlg para Delégua
  .vscode/launch.json
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-visualg.ts
  fontes/tradutores/tradutor-reverso-javascript.ts
  fontes/tradutores/tradutor-visualg.ts
  testes/tradutores/tradutor-visualg.test.ts
  testes/visualg/interpretador.test.ts
Labels: em andamento
