Repository DesignLiquido/delegua, pull requests merged in 2023-05, with the labels that each got.

#391 Interpretador birl
  .vscode/launch.json
  fontes/analisador-semantico/analisador-semantico.ts
  fontes/avaliador-sintatico/avaliador-sintatico-base.ts
  fontes/avaliador-sintatico/avaliador-sintatico.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-birl.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-egua-classico.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-eguap.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-guarani.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-mapler.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-portugol-ipt.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-portugol-studio.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-visualg.ts
  fontes/construtos/atribuicao-por-indice.ts
  fontes/construtos/index.ts
  fontes/interfaces/resolvedor-interface.ts
  fontes/interfaces/visitante-comum-interface.ts
  fontes/interpretador/dialetos/birl/interpretador-birl.ts
  fontes/interpretador/dialetos/egua-classico/interpretador-egua-classico.ts
  fontes/interpretador/dialetos/egua-classico/resolvedor/resolvedor.ts
  fontes/interpretador/dialetos/portugol-ipt/interpretador-portugol-ipt.ts
  fontes/interpretador/interpretador-base.ts
  fontes/lexador/dialetos/lexador-birl.ts
  fontes/tipos-de-simbolos/birl.ts
  fontes/tradutores/tradutor-javascript.ts
  fontes/tradutores/tradutor-visualg.ts
  testes/birl/avaliador-sintatico.test.ts
  testes/birl/interpretador.test.ts
  testes/birl/lexador.test.ts
Labels: melhoria

#390 #384 Melhoria micro lexador e testes para interpolação
  .vscode/launch.json
  fontes/avaliador-sintatico/avaliador-sintatico.ts
  fontes/avaliador-sintatico/micro-avaliador-sintatico.ts
  fontes/construtos/literal.ts
  fontes/interpretador/inferenciador.ts
  fontes/interpretador/interpretador-base.ts
  fontes/lexador/micro-lexador.ts
  testes/interpretador.test.ts
  testes/micro-avaliador-sintatico.test.ts
  testes/micro-lexador.test.ts
Labels: em andamento

#399 Avaliador resolve
  .vscode/launch.json
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-birl.ts
  testes/birl/avaliador-sintatico.test.ts
  testes/birl/interpretador.test.ts
Labels: melhoria

#406 Modificação interpretador Birl:
  fontes/avaliador-sintatico/avaliador-sintatico-base.ts
  fontes/tipos-de-simbolos/comum.ts
  testes/birl/interpretador.test.ts
Labels: melhoria

#409 Adicionando declaração de função outros tipos.
  testes/birl/avaliador-sintatico.test.ts
Labels: good first issue

#405 #392 Atribuição de variaveis na mesma linha
  fontes/avaliador-sintatico/avaliador-sintatico-base.ts
  fontes/avaliador-sintatico/avaliador-sintatico.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-egua-classico.ts
  fontes/avaliador-sintatico/dialetos/avaliador-sintatico-eguap.ts
  fontes/interfaces/avaliador-sintatico-interface.ts
  fontes/interpretador/interpretador-base.ts
  fontes/tradutores/tradutor-javascript.ts
  testes/interpretador.test.ts
Labels: melhoria
